//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-02-26 13:41:20
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.dao.impl;

import org.springframework.stereotype.Repository;
import com.bonc.quickframework.dao.IGeneratorDataTypeDao;
import com.bonc.quickframework.entity.GeneratorDataType;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
@Repository(value="generatorDataTypeDao")
public class GeneratorDataTypeDaoImpl extends BaseDaoImpl<GeneratorDataType,java.lang.Long> implements IGeneratorDataTypeDao {

}
