//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-14 10:01:22
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.dao.impl;

import org.springframework.stereotype.Repository;
import com.bonc.quickframework.dao.IGeneratorDbserverDao;
import com.bonc.quickframework.entity.GeneratorDbserver;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
@Repository(value="generatorDbserverDao")
public class GeneratorDbserverDaoImpl extends BaseDaoImpl<GeneratorDbserver,java.lang.Long> implements IGeneratorDbserverDao {

}
