//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-03-25 15:47:25
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.dao.impl;

import org.springframework.stereotype.Repository;
import com.bonc.quickframework.dao.IGenTemplateDao;
import com.bonc.quickframework.entity.GenTemplate;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
@Repository(value="genTemplateDao")
public class GenTemplateDaoImpl extends BaseDaoImpl<GenTemplate,java.lang.Long> implements IGenTemplateDao {

}
