//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-14 10:01:22
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.web.action.original;

import javax.annotation.Resource;
import com.bonc.quickframework.bean.GeneratorDbserverBean;
import com.bonc.quickframework.entity.GeneratorDbserver;
import com.bonc.quickframework.service.IGeneratorDbserverService;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class AbstractGeneratorDbserverAction extends BaseAction {
	
	GeneratorDbserverBean bean=new GeneratorDbserverBean();
	
	@Resource(name = "generatorDbserverService")
	protected IGeneratorDbserverService generatorDbserverService;


	public GeneratorDbserverBean getBean() {
		return bean;
	}

	public void setBean(GeneratorDbserverBean bean) {
		this.bean = bean;
	}
	
	public String list() {
		List dataList = this.generatorDbserverService.findList(this.getBean());
		this.getBean().setObjectList(dataList);
		return "list";
	}
	public String add() {
		return "add";
	}
	public String addDo() {
		this.generatorDbserverService.saveOrUpdate(this.getBean().getGeneratorDbserver());
		return SUCCESS;
	}
	public String edit() {
		GeneratorDbserver generatorDbserver=this.generatorDbserverService.findById(this.getBean().getGeneratorDbserver().getId());
		this.getBean().setGeneratorDbserver(generatorDbserver);
		return "edit";
	}
	public String editDo() {
		this.generatorDbserverService.saveOrUpdate(this.getBean().getGeneratorDbserver());
		return SUCCESS;
	}
	public String delete() {
		this.generatorDbserverService.delete(this.getBean().getGeneratorDbserver().getId());
		return SUCCESS;
	}
}
