//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-03-04 15:08:12
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.web.action.original;

import javax.annotation.Resource;
import com.bonc.quickframework.bean.GeneratorUiBean;
import com.bonc.quickframework.entity.GeneratorUi;
import com.bonc.quickframework.service.IGeneratorUiService;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class AbstractGeneratorUiAction extends BaseAction {
	
	GeneratorUiBean bean=new GeneratorUiBean();
	
	@Resource(name = "generatorUiService")
	protected IGeneratorUiService generatorUiService;


	public GeneratorUiBean getBean() {
		return bean;
	}

	public void setBean(GeneratorUiBean bean) {
		this.bean = bean;
	}
	
	public String list() {
		List dataList = this.generatorUiService.findList(this.getBean());
		this.getBean().setObjectList(dataList);
		return "list";
	}
	public String add() {
		return "add";
	}
	public String addDo() {
		this.generatorUiService.saveOrUpdate(this.getBean().getGeneratorUi());
		return SUCCESS;
	}
	public String edit() {
		GeneratorUi generatorUi=this.generatorUiService.findById(this.getBean().getGeneratorUi().getId());
		this.getBean().setGeneratorUi(generatorUi);
		return "edit";
	}
	public String editDo() {
		this.generatorUiService.saveOrUpdate(this.getBean().getGeneratorUi());
		return SUCCESS;
	}
	public String delete() {
		this.generatorUiService.delete(this.getBean().getGeneratorUi().getId());
		return SUCCESS;
	}
}
