//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-19 11:56:16
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.web.action.original;

import javax.annotation.Resource;
import com.bonc.quickframework.bean.GeneratorMethodParamBean;
import com.bonc.quickframework.entity.GeneratorMethodParam;
import com.bonc.quickframework.service.IGeneratorMethodParamService;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class AbstractGeneratorMethodParamAction extends BaseAction {
	
	GeneratorMethodParamBean bean=new GeneratorMethodParamBean();
	
	@Resource(name = "generatorMethodParamService")
	protected IGeneratorMethodParamService generatorMethodParamService;


	public GeneratorMethodParamBean getBean() {
		return bean;
	}

	public void setBean(GeneratorMethodParamBean bean) {
		this.bean = bean;
	}
	
	public String list() {
		List dataList = this.generatorMethodParamService.findList(this.getBean());
		this.getBean().setObjectList(dataList);
		return "list";
	}
	public String add() {
		return "add";
	}
	public String addDo() {
		this.generatorMethodParamService.saveOrUpdate(this.getBean().getGeneratorMethodParam());
		return SUCCESS;
	}
	public String edit() {
		GeneratorMethodParam generatorMethodParam=this.generatorMethodParamService.findById(this.getBean().getGeneratorMethodParam().getId());
		this.getBean().setGeneratorMethodParam(generatorMethodParam);
		return "edit";
	}
	public String editDo() {
		this.generatorMethodParamService.saveOrUpdate(this.getBean().getGeneratorMethodParam());
		return SUCCESS;
	}
	public String delete() {
		this.generatorMethodParamService.delete(this.getBean().getGeneratorMethodParam().getId());
		return SUCCESS;
	}
}
