//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-14 10:01:23
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.web.action.original;

import javax.annotation.Resource;
import com.bonc.quickframework.bean.GeneratorWebserverBean;
import com.bonc.quickframework.entity.GeneratorWebserver;
import com.bonc.quickframework.service.IGeneratorWebserverService;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class AbstractGeneratorWebserverAction extends BaseAction {
	
	GeneratorWebserverBean bean=new GeneratorWebserverBean();
	
	@Resource(name = "generatorWebserverService")
	protected IGeneratorWebserverService generatorWebserverService;


	public GeneratorWebserverBean getBean() {
		return bean;
	}

	public void setBean(GeneratorWebserverBean bean) {
		this.bean = bean;
	}
	
	public String list() {
		List dataList = this.generatorWebserverService.findList(this.getBean());
		this.getBean().setObjectList(dataList);
		return "list";
	}
	public String add() {
		return "add";
	}
	public String addDo() {
		this.generatorWebserverService.saveOrUpdate(this.getBean().getGeneratorWebserver());
		return SUCCESS;
	}
	public String edit() {
		GeneratorWebserver generatorWebserver=this.generatorWebserverService.findById(this.getBean().getGeneratorWebserver().getId());
		this.getBean().setGeneratorWebserver(generatorWebserver);
		return "edit";
	}
	public String editDo() {
		this.generatorWebserverService.saveOrUpdate(this.getBean().getGeneratorWebserver());
		return SUCCESS;
	}
	public String delete() {
		this.generatorWebserverService.delete(this.getBean().getGeneratorWebserver().getId());
		return SUCCESS;
	}
}
