//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-03-25 15:47:29
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.web.action.original;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.bonc.quickframework.bean.GenPropTypeBean;
import com.bonc.quickframework.bean.ResultInfo;
import com.bonc.quickframework.entity.GenPropType;
import com.bonc.quickframework.service.IGenPropTypeService;
import com.bonc.quickframework.util.*;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class AbstractGenPropTypeAction extends BaseAction {
	
	GenPropTypeBean bean=new GenPropTypeBean();
	
	@Resource(name = "genPropTypeService")
	protected IGenPropTypeService genPropTypeService;


	public GenPropTypeBean getBean() {
		return bean;
	}

	public void setBean(GenPropTypeBean bean) {
		this.bean = bean;
	}
	
	public String list() {
		List dataList = this.genPropTypeService.findList(this.getBean());
		this.getBean().setObjectList(dataList);
		return "list";
	}
	public String add() {
		return "add";
	}
	public String addDo() {
		this.genPropTypeService.saveOrUpdate(this.getBean().getGenPropType());
		return SUCCESS;
	}
	public String edit() {
		GenPropType genPropType=this.genPropTypeService.findById(this.getBean().getGenPropType().getId());
		this.getBean().setGenPropType(genPropType);
		return "edit";
	}
	public String editDo() {
		this.genPropTypeService.saveOrUpdate(this.getBean().getGenPropType());
		return SUCCESS;
	}
	public String delete() {
		this.genPropTypeService.delete(this.getBean().getGenPropType().getId());
		return SUCCESS;
	}
	
	/**
	 * 异步删除
	 */
	public void asyncDeleteAll() {
		try {
			String idString = this.getBean().getIdList();
			if(idString == null || "".endsWith(idString.trim())){
				ServletUtil.sendAsJson(response,new ResultInfo(false,"id is null").toJSONString() );
			}else{
				List<Long> ids = new ArrayList<Long>();
				String[] tmps = idString.split(",");
				for (String tmp : tmps) {
					if(tmp!=null && !"".equals(tmp.trim())){
						ids.add(Long.parseLong(tmp));
					}
				}
				this.genPropTypeService.deleteByCollection(this.genPropTypeService.findList(ids));
			}
			ServletUtil.sendAsJson(response,new ResultInfo(true,"删除成功").toJSONString() );
		} catch (Exception e) {
			e.printStackTrace();
			ServletUtil.sendAsJson(response,new ResultInfo(false,e.getMessage()).toJSONString() );
		}
	}
	
}
