//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-02-26 13:41:20
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.web.action.original;

import javax.annotation.Resource;
import com.bonc.quickframework.bean.GeneratorDataTypeBean;
import com.bonc.quickframework.entity.GeneratorDataType;
import com.bonc.quickframework.service.IGeneratorDataTypeService;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class AbstractGeneratorDataTypeAction extends BaseAction {
	
	GeneratorDataTypeBean bean=new GeneratorDataTypeBean();
	
	@Resource(name = "generatorDataTypeService")
	protected IGeneratorDataTypeService generatorDataTypeService;


	public GeneratorDataTypeBean getBean() {
		return bean;
	}

	public void setBean(GeneratorDataTypeBean bean) {
		this.bean = bean;
	}
	
	public String list() {
		List dataList = this.generatorDataTypeService.findList(this.getBean());
		this.getBean().setObjectList(dataList);
		return "list";
	}
	public String add() {
		return "add";
	}
	public String addDo() {
		this.generatorDataTypeService.saveOrUpdate(this.getBean().getGeneratorDataType());
		return SUCCESS;
	}
	public String edit() {
		GeneratorDataType generatorDataType=this.generatorDataTypeService.findById(this.getBean().getGeneratorDataType().getId());
		this.getBean().setGeneratorDataType(generatorDataType);
		return "edit";
	}
	public String editDo() {
		this.generatorDataTypeService.saveOrUpdate(this.getBean().getGeneratorDataType());
		return SUCCESS;
	}
	public String delete() {
		this.generatorDataTypeService.delete(this.getBean().getGeneratorDataType().getId());
		return SUCCESS;
	}
}
