//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-14 10:01:24
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.web.action.original;

import javax.annotation.Resource;
import com.bonc.quickframework.bean.GeneratorProjectBean;
import com.bonc.quickframework.entity.GeneratorProject;
import com.bonc.quickframework.service.IGeneratorProjectService;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class AbstractGeneratorProjectAction extends BaseAction {
	
	GeneratorProjectBean bean=new GeneratorProjectBean();
	
	@Resource(name = "generatorProjectService")
	protected IGeneratorProjectService generatorProjectService;


	public GeneratorProjectBean getBean() {
		return bean;
	}

	public void setBean(GeneratorProjectBean bean) {
		this.bean = bean;
	}
	
	public String list() {
		List dataList = this.generatorProjectService.findList(this.getBean());
		this.getBean().setObjectList(dataList);
		return "list";
	}
	public String add() {
		return "add";
	}
	public String addDo() {
		this.generatorProjectService.saveOrUpdate(this.getBean().getGeneratorProject());
		return SUCCESS;
	}
	public String edit() {
		GeneratorProject generatorProject=this.generatorProjectService.findById(this.getBean().getGeneratorProject().getId());
		this.getBean().setGeneratorProject(generatorProject);
		return "edit";
	}
	public String editDo() {
		this.generatorProjectService.saveOrUpdate(this.getBean().getGeneratorProject());
		return SUCCESS;
	}
	public String delete() {
		this.generatorProjectService.delete(this.getBean().getGeneratorProject().getId());
		return SUCCESS;
	}
}
