//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-19 11:56:15
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.web.action.original;

import javax.annotation.Resource;
import com.bonc.quickframework.bean.GeneratorServiceMethodBean;
import com.bonc.quickframework.entity.GeneratorServiceMethod;
import com.bonc.quickframework.service.IGeneratorServiceMethodService;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class AbstractGeneratorServiceMethodAction extends BaseAction {
	
	GeneratorServiceMethodBean bean=new GeneratorServiceMethodBean();
	
	@Resource(name = "generatorServiceMethodService")
	protected IGeneratorServiceMethodService generatorServiceMethodService;


	public GeneratorServiceMethodBean getBean() {
		return bean;
	}

	public void setBean(GeneratorServiceMethodBean bean) {
		this.bean = bean;
	}
	
	public String list() {
		List dataList = this.generatorServiceMethodService.findList(this.getBean());
		this.getBean().setObjectList(dataList);
		return "list";
	}
	public String add() {
		return "add";
	}
	public String addDo() {
		this.generatorServiceMethodService.saveOrUpdate(this.getBean().getGeneratorServiceMethod());
		return SUCCESS;
	}
	public String edit() {
		GeneratorServiceMethod generatorServiceMethod=this.generatorServiceMethodService.findById(this.getBean().getGeneratorServiceMethod().getId());
		this.getBean().setGeneratorServiceMethod(generatorServiceMethod);
		return "edit";
	}
	public String editDo() {
		this.generatorServiceMethodService.saveOrUpdate(this.getBean().getGeneratorServiceMethod());
		return SUCCESS;
	}
	public String delete() {
		this.generatorServiceMethodService.delete(this.getBean().getGeneratorServiceMethod().getId());
		return SUCCESS;
	}
}
