//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-14 10:01:25
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package ${basepackage}.bean;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

//@XmlRootElement(name="PageInfo")
public class PageInfo implements Serializable{

	/**
	 * 分页大小，默认值为10
	 * */
	private int pageSize = 10;
	/**
	 * 总页数
	 * */
	private int totalPages = 0;
	/**
	 * 当前页数
	 * */
	private int currentPage = 1;
	/**
	 * 记录总条数
	 * */
	private int totalCounts = 0;
	/**
	 * 当前页开始显示记录数
	 * */
	private int firstResult = 0;
	
	/**
	 * 排序类型(ASC,DESC)
	 */
	private String sortType;
	/**
	 * 排序属性
	 */
	private String sortAttribute;
	
	/**
	 * 精确匹配 and
	 */
	private Map<String, Object> equalsMap = new HashMap<String, Object>();
	
	/**
	 * 模糊匹配 
	 */
	private Map<String, Object> matchMap=new HashMap<String, Object>();
	
	/**
	 * 大于等于
	 *//*
	private Map<String, Object> gteMap=new HashMap<String, Object>();
	*//**
	 * 小于等于
	 *//*
	private Map<String, Object> lteMap=new HashMap<String, Object>();*/
	
	public int getPageSize() {
		return pageSize;
	}
	public void setPageSize(int pageSize) {
		this.pageSize = pageSize;
	}
	public int getTotalPages() {
		return (this.totalCounts - 1) / this.pageSize + 1;
	}
	public void setTotalPages(int totalPages) {
		this.totalPages = totalPages;
	}
	public int getCurrentPage() {
		return currentPage;
	}
	public void setCurrentPage(int currentPage) {
		this.currentPage = currentPage;
	}
	public int getTotalCounts() {
		return totalCounts;
	}
	public void setTotalCounts(int totalCounts) {
		this.totalCounts = totalCounts;
	}
	public int getFirstResult() {
		return (currentPage - 1) * pageSize ;
	}
	public void setFirstResult(int firstResult) {
		this.firstResult = firstResult;
	}
	public String getSortType() {
		return sortType;
	}
	public void setSortType(String sortType) {
		this.sortType = sortType;
	}
	public String getSortAttribute() {
		return sortAttribute;
	}
	public void setSortAttribute(String sortAttribute) {
		this.sortAttribute = sortAttribute;
	}
	public Map<String, Object> getEqualsMap() {
		return equalsMap;
	}
	public void setEqualsMap(Map<String, Object> equalsMap) {
		this.equalsMap = equalsMap;
	}
	public Map<String, Object> getMatchMap() {
		return matchMap;
	}
	public void setMatchMap(Map<String, Object> matchMap) {
		this.matchMap = matchMap;
	}
	/*public Map<String, Object> getGteMap() {
		return gteMap;
	}
	public void setGteMap(Map<String, Object> gteMap) {
		this.gteMap = gteMap;
	}
	public Map<String, Object> getLteMap() {
		return lteMap;
	}
	public void setLteMap(Map<String, Object> lteMap) {
		this.lteMap = lteMap;
	}*/
	
}

