//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-03-25 15:47:31
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.bean;

import com.bonc.quickframework.entity.GenController;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class GenControllerBean extends BaseBean {

	GenController genController = new GenController();

	/*get、set*/
	public GenController getGenController() {
		return genController;
	}

	public void setGenController(GenController genController) {
		this.genController = genController;
	}
}
