//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-14 10:01:23
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.bean;

import com.bonc.quickframework.entity.GeneratorWebserver;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class GeneratorWebserverBean extends BaseBean {

	GeneratorWebserver generatorWebserver = new GeneratorWebserver();

	/*get、set*/
	public GeneratorWebserver getGeneratorWebserver() {
		return generatorWebserver;
	}

	public void setGeneratorWebserver(GeneratorWebserver generatorWebserver) {
		this.generatorWebserver = generatorWebserver;
	}
}
