//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-03-25 15:47:30
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.bean;

import com.bonc.quickframework.entity.GenModelProperty;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class GenModelPropertyBean extends BaseBean {

	GenModelProperty genModelProperty = new GenModelProperty();

	/*get、set*/
	public GenModelProperty getGenModelProperty() {
		return genModelProperty;
	}

	public void setGenModelProperty(GenModelProperty genModelProperty) {
		this.genModelProperty = genModelProperty;
	}
}
