//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-19 11:56:14
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.dao;

import com.bonc.quickframework.dao.IBaseDao;
import com.bonc.quickframework.entity.GeneratorService;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 public interface IGeneratorServiceDao extends IBaseDao<GeneratorService,java.lang.Long> {

}