//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-14 10:01:22
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.service.impl;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import com.bonc.quickframework.dao.IBaseDao;
import com.bonc.quickframework.dao.IGeneratorDbserverDao;
import com.bonc.quickframework.entity.GeneratorDbserver;
import com.bonc.quickframework.service.IGeneratorDbserverService;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
@Service(value = "generatorDbserverService")
public class GeneratorDbserverServiceImpl extends BaseServiceImpl<GeneratorDbserver,java.lang.Long> implements IGeneratorDbserverService {
	@Resource(name = "generatorDbserverDao")
	private IGeneratorDbserverDao generatorDbserverDao;

	@Override
	protected IBaseDao<GeneratorDbserver,java.lang.Long> getCurrentDao() {
		return generatorDbserverDao;
	}
}
