//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-19 11:56:16
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.service.impl;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import com.bonc.quickframework.dao.IBaseDao;
import com.bonc.quickframework.dao.IGeneratorMethodParamDao;
import com.bonc.quickframework.entity.GeneratorMethodParam;
import com.bonc.quickframework.service.IGeneratorMethodParamService;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
@Service(value = "generatorMethodParamService")
public class GeneratorMethodParamServiceImpl extends BaseServiceImpl<GeneratorMethodParam,java.lang.Long> implements IGeneratorMethodParamService {
	@Resource(name = "generatorMethodParamDao")
	private IGeneratorMethodParamDao generatorMethodParamDao;

	@Override
	protected IBaseDao<GeneratorMethodParam,java.lang.Long> getCurrentDao() {
		return generatorMethodParamDao;
	}
}
