//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-19 11:56:15
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.service.impl;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import com.bonc.quickframework.dao.IBaseDao;
import com.bonc.quickframework.dao.IGeneratorServiceMethodDao;
import com.bonc.quickframework.entity.GeneratorServiceMethod;
import com.bonc.quickframework.service.IGeneratorServiceMethodService;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
@Service(value = "generatorServiceMethodService")
public class GeneratorServiceMethodServiceImpl extends BaseServiceImpl<GeneratorServiceMethod,java.lang.Long> implements IGeneratorServiceMethodService {
	@Resource(name = "generatorServiceMethodDao")
	private IGeneratorServiceMethodDao generatorServiceMethodDao;

	@Override
	protected IBaseDao<GeneratorServiceMethod,java.lang.Long> getCurrentDao() {
		return generatorServiceMethodDao;
	}
}
