//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-14 10:01:25
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.service.impl;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import com.bonc.quickframework.dao.IBaseDao;
import com.bonc.quickframework.dao.IGeneratorFieldDao;
import com.bonc.quickframework.entity.GeneratorField;
import com.bonc.quickframework.service.IGeneratorFieldService;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
@Service(value = "generatorFieldService")
public class GeneratorFieldServiceImpl extends BaseServiceImpl<GeneratorField,java.lang.Long> implements IGeneratorFieldService {
	@Resource(name = "generatorFieldDao")
	private IGeneratorFieldDao generatorFieldDao;

	@Override
	protected IBaseDao<GeneratorField,java.lang.Long> getCurrentDao() {
		return generatorFieldDao;
	}
}
