//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-03-25 15:47:26
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.service.impl;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import com.bonc.quickframework.dao.IBaseDao;
import com.bonc.quickframework.dao.IGenUiDao;
import com.bonc.quickframework.entity.GenUi;
import com.bonc.quickframework.service.IGenUiService;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
@Service(value = "genUiService")
public class GenUiServiceImpl extends BaseServiceImpl<GenUi,java.lang.Long> implements IGenUiService {
	@Resource(name = "genUiDao")
	private IGenUiDao genUiDao;

	@Override
	protected IBaseDao<GenUi,java.lang.Long> getCurrentDao() {
		return genUiDao;
	}
}
