//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-03-25 15:47:33
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.service.impl;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import com.bonc.quickframework.dao.IBaseDao;
import com.bonc.quickframework.dao.IGenViewDao;
import com.bonc.quickframework.entity.GenView;
import com.bonc.quickframework.service.IGenViewService;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
@Service(value = "genViewService")
public class GenViewServiceImpl extends BaseServiceImpl<GenView,java.lang.Long> implements IGenViewService {
	@Resource(name = "genViewDao")
	private IGenViewDao genViewDao;

	@Override
	protected IBaseDao<GenView,java.lang.Long> getCurrentDao() {
		return genViewDao;
	}
}
