//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-14 10:01:25
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.web.action;

import javax.annotation.Resource;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import com.bonc.quickframework.factory.serviceContext;
import com.bonc.quickframework.service.IGeneratorFieldService;
import com.bonc.quickframework.service.IGeneratorProjectService;
import com.bonc.quickframework.web.action.original.AbstractGeneratorEntityAction;
import com.opensymphony.xwork2.ActionContext;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */

@Controller(value = "generatorEntityAction")
@Scope(value = "prototype")
public class GeneratorEntityAction extends AbstractGeneratorEntityAction {

	@Resource(name = "generatorProjectService")
	protected IGeneratorProjectService generatorProjectService;

	@Override
	public String list() {
		Long projectId = this.getBean().getGeneratorEntity().getProjectId();
		if (projectId != null && projectId != 0) {
			this.getBean().getPageInfo().getQuerys()
					.put("projectId", projectId);
		}
		String code = this.getBean().getGeneratorEntity().getCode();
		if(code != null && !"".equals(code.toString())){
			this.getBean().getPageInfo().getMatchMaps().put("code", code);
		}
		String name = this.getBean().getGeneratorEntity().getName();
		if(name != null && !"".equals(name.toString())){
			this.getBean().getPageInfo().getMatchMaps().put("name", name);
		}
		return super.list();
	}
}
