//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-13 11:37:22
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.web.action;

import java.io.File;

import javax.annotation.Resource;

import org.apache.struts2.ServletActionContext;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import com.bonc.quickframework.bean.ResultInfo;
import com.bonc.quickframework.entity.GeneratorDbserver;
import com.bonc.quickframework.entity.GeneratorProject;
import com.bonc.quickframework.entity.GeneratorWebserver;
import com.bonc.quickframework.generator.GeneratorFacade;
import com.bonc.quickframework.service.IGeneratorDbserverService;
import com.bonc.quickframework.service.IGeneratorWebserverService;
import com.bonc.quickframework.util.ServletUtil;
import com.bonc.quickframework.web.action.original.AbstractGeneratorProjectAction;
import com.opensymphony.xwork2.ActionContext;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */

@Controller(value = "generatorProjectAction")
@Scope(value = "prototype")
public class GeneratorProjectAction extends AbstractGeneratorProjectAction {

	@Resource(name = "generatorDbserverService")
	protected IGeneratorDbserverService dbService;

	@Resource(name = "generatorWebserverService")
	protected IGeneratorWebserverService webService;

	
	@Override
	public String add() {
		this.findServer();
		return super.add();
	};
	@Override
	public String edit() {
		this.findServer();
		return super.edit();
	}
	
	private void findServer(){
		ActionContext.getContext().put("dbServers", dbService.loadAll());
		ActionContext.getContext().put("webServers", webService.loadAll());
	}
	/**
	 * 生成代码
	 */
	public void generate() {
		String result = "";
		try {
			String delete = request.getParameter("delete");
			
			Long projectId = this.getBean().getGeneratorProject().getId();
			GeneratorProject project = this.generatorProjectService
					.findById(projectId);
			GeneratorDbserver db = dbService.findById(project.getDbserverId());
			GeneratorWebserver web = webService.findById(project
					.getWebserverId());

			String basePath = ServletActionContext.getServletContext()
					.getRealPath(File.separator);
			

			String inputPath = basePath + "templates" + File.separator + project.getTemaplateName();
			String outputPath = project.getPath();

			GeneratorFacade.makeProjectCode(project, web, db,
					project.getGeneratorEntitys(),project.getGeneratorServices(),
					inputPath, outputPath,"1".equals(delete));
			result = new ResultInfo(true, "生成代码成功").toJSONString();
		} catch (Exception e) {
			e.printStackTrace();
			String msg= e.getMessage()!=null? e.getMessage():e.getStackTrace().toString();
			result = new ResultInfo(false, msg).toJSONString();
		}
		ServletUtil.sendAsJson(response, result);
	}

	/**
	 * 发布
	 */
	public void publish() {
		String result = "";
		try {
			GeneratorFacade.compileAndDeploy(request.getParameter("codePath"));
			result = new ResultInfo(true, "部署成功").toJSONString();
		} catch (Exception e) {
			String msg= e.getMessage()!=null? e.getMessage():e.getStackTrace().toString();
			result = new ResultInfo(false, msg).toJSONString();
		}
		ServletUtil.sendAsJson(response, result);
	}

	/**
	 * 清理
	 */
	public void clean() {
		String result = "";
		try {
			GeneratorFacade.clean(request.getParameter("codePath"));
			result = new ResultInfo(true, "清理完成").toJSONString();
		} catch (Exception e) {
			String msg= e.getMessage()!=null? e.getMessage():e.getStackTrace().toString();
			result = new ResultInfo(false, msg).toJSONString();
		}
		ServletUtil.sendAsJson(response, result);
	}
}
