//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-19 11:56:14
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.web.action;

import java.util.List;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import com.bonc.quickframework.entity.GeneratorService;
import com.bonc.quickframework.service.IGeneratorProjectService;
import com.bonc.quickframework.web.action.original.AbstractGeneratorServiceAction;
import com.opensymphony.xwork2.ActionContext;

import java.util.*;

import javax.annotation.Resource;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
@Controller(value = "generatorServiceAction")
@Scope(value = "prototype")
public class GeneratorServiceAction extends AbstractGeneratorServiceAction {

	@Resource(name = "generatorProjectService")
	protected IGeneratorProjectService generatorProjectService;

	@Override
	public String list() {
		Long projectId = this.getBean().getGeneratorService().getProjectId();
		if (projectId != null && projectId != 0) {
			this.getBean().getPageInfo().getQuerys()
					.put("projectId", projectId);
		}
		return super.list();
	}

	@Override
	public String add() {
		this.findProjects();
		return super.add();
	};

	@Override
	public String edit() {
		this.findProjects();
		return super.edit();
	}

	private void findProjects(){
		ActionContext.getContext().put("generatorProjects", generatorProjectService.loadAll());
	}
}
