//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-03-25 15:47:33
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.web.action;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import com.bonc.quickframework.bean.GenUiDetailBean;
import com.bonc.quickframework.bean.ResultInfo;
import com.bonc.quickframework.entity.GenUi;
import com.bonc.quickframework.entity.GenView;
import com.bonc.quickframework.factory.serviceContext;
import com.bonc.quickframework.util.ServletUtil;
import com.bonc.quickframework.web.action.original.AbstractGenViewAction;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */

@Controller(value = "genViewAction")
@Scope(value = "prototype")
public class GenViewAction extends AbstractGenViewAction {

	public void loadUis() {
		try {
			GenUiDetailBean detailBean = new GenUiDetailBean();
			detailBean.getPageInfo().setPageSize(Integer.MAX_VALUE);
			String uiTypeId = request.getParameter("uiTypeId");
			if(uiTypeId!=null && !"".equals(uiTypeId)){
				detailBean.getPageInfo().getQuerys().put("uiTypeId", Long.parseLong(uiTypeId));
			}
			List list = new serviceContext().getGenUiDetailService().findList(detailBean);
			Map params=new HashMap<String, Object>();
			params.put("data", list);
			ResultInfo resultInfo = new ResultInfo(true, "", params);
			ServletUtil.sendAsJson(response, resultInfo.toJSONString());
		} catch (Exception e) {
			e.printStackTrace();
			ServletUtil.sendAsJson(response,
					new ResultInfo(false, e.getMessage()).toJSONString());
		}
	}

}
