//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-03-25 15:47:31
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.entity;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class GenController implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	
	//columns START
	private java.lang.Long id;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.Long modelId;
	private java.lang.Long projectId;
	//columns END

	public GenController(){
	}

	public GenController(
		java.lang.Long id
	){
		this.id = id;
	}

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	public java.lang.Long getId() {
		return this.id;
	}
	public void setCode(java.lang.String value) {
		this.code = value;
	}
	
	public java.lang.String getCode() {
		return this.code;
	}
	public void setName(java.lang.String value) {
		this.name = value;
	}
	
	public java.lang.String getName() {
		return this.name;
	}
	public void setModelId(java.lang.Long value) {
		this.modelId = value;
	}
	
	public java.lang.Long getModelId() {
		return this.modelId;
	}
	public void setProjectId(java.lang.Long value) {
		this.projectId = value;
	}
	
	public java.lang.Long getProjectId() {
		return this.projectId;
	}
	
	private Set<GenControlerMethod> genControlerMethods = new HashSet<GenControlerMethod>(0);
	public void setGenControlerMethods(Set genControlerMethod){
		this.genControlerMethods = genControlerMethod;
	}
	
	public Set<GenControlerMethod> getGenControlerMethods() {
		return genControlerMethods;
	}
	
	private Set<GenView> genViews = new HashSet<GenView>(0);
	public void setGenViews(Set genView){
		this.genViews = genView;
	}
	
	public Set<GenView> getGenViews() {
		return genViews;
	}
	
	private GenModel genModel;
	
	public void setGenModel(GenModel genModel){
		this.genModel = genModel;
	}
	
	public GenModel getGenModel() {
		return genModel;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("Code",getCode())
			.append("Name",getName())
			.append("ModelId",getModelId())
			.append("ProjectId",getProjectId())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.append(getCode())
			.append(getName())
			.append(getModelId())
			.append(getProjectId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof GenController == false) return false;
		if(this == obj) return true;
		GenController other = (GenController)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.append(getCode(),other.getCode())
			.append(getName(),other.getName())
			.append(getModelId(),other.getModelId())
			.append(getProjectId(),other.getProjectId())
			.isEquals();
	}
}

