//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-03-04 15:08:12
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.entity;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class GeneratorUi implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	
	//columns START
	private java.lang.Long id;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.String type;
	private java.lang.Long implementType;
	private java.lang.String script;
	private java.lang.Long sequence;
	//columns END

	public GeneratorUi(){
	}

	public GeneratorUi(
		java.lang.Long id
	){
		this.id = id;
	}

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	public java.lang.Long getId() {
		return this.id;
	}
	public void setCode(java.lang.String value) {
		this.code = value;
	}
	
	public java.lang.String getCode() {
		return this.code;
	}
	public void setName(java.lang.String value) {
		this.name = value;
	}
	
	public java.lang.String getName() {
		return this.name;
	}
	public void setType(java.lang.String value) {
		this.type = value;
	}
	
	public java.lang.String getType() {
		return this.type;
	}
	
	public java.lang.Long getImplementType() {
		return implementType;
	}

	public void setImplementType(java.lang.Long implementType) {
		this.implementType = implementType;
	}

	public void setScript(java.lang.String value) {
		this.script = value;
	}
	
	public java.lang.String getScript() {
		return this.script;
	}
	public void setSequence(java.lang.Long value) {
		this.sequence = value;
	}
	
	public java.lang.Long getSequence() {
		return this.sequence;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("Code",getCode())
			.append("Name",getName())
			.append("Type",getType())
			.append("implementType",getImplementType())
			.append("Script",getScript())
			.append("Sequence",getSequence())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.append(getCode())
			.append(getName())
			.append(getType())
			.append(getImplementType())
			.append(getScript())
			.append(getSequence())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof GeneratorUi == false) return false;
		if(this == obj) return true;
		GeneratorUi other = (GeneratorUi)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.append(getCode(),other.getCode())
			.append(getName(),other.getName())
			.append(getType(),other.getType())
			.append(getImplementType(),other.getImplementType())
			.append(getScript(),other.getScript())
			.append(getSequence(),other.getSequence())
			.isEquals();
	}
}

