//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-18 15:28:40
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.entity;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class GeneratorProject implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	
	//columns START
	private java.lang.Long id;
	private java.lang.String path;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.String basepackage;
	private java.lang.String temaplateName;
	private java.lang.Long dbserverId;
	private java.lang.Long webserverId;
	//columns END

	public GeneratorProject(){
	}

	public GeneratorProject(
		java.lang.Long id
	){
		this.id = id;
	}

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	public java.lang.Long getId() {
		return this.id;
	}
	public void setPath(java.lang.String value) {
		this.path = value;
	}
	
	public java.lang.String getPath() {
		return this.path;
	}
	public void setCode(java.lang.String value) {
		this.code = value;
	}
	
	public java.lang.String getCode() {
		return this.code;
	}
	public void setName(java.lang.String value) {
		this.name = value;
	}
	
	public java.lang.String getName() {
		return this.name;
	}
	public void setBasepackage(java.lang.String value) {
		this.basepackage = value;
	}
	
	public java.lang.String getBasepackage() {
		return this.basepackage;
	}
	public void setTemaplateName(java.lang.String value) {
		this.temaplateName = value;
	}
	
	public java.lang.String getTemaplateName() {
		return this.temaplateName;
	}
	public void setDbserverId(java.lang.Long value) {
		this.dbserverId = value;
	}
	
	public java.lang.Long getDbserverId() {
		return this.dbserverId;
	}
	public void setWebserverId(java.lang.Long value) {
		this.webserverId = value;
	}
	
	public java.lang.Long getWebserverId() {
		return this.webserverId;
	}
	
	private Set<GeneratorService> generatorServices = new HashSet<GeneratorService>(0);
	public void setGeneratorServices(Set generatorService){
		this.generatorServices = generatorService;
	}
	
	public Set<GeneratorService> getGeneratorServices() {
		return generatorServices;
	}
	
	private Set<GeneratorEntity> generatorEntitys = new HashSet<GeneratorEntity>(0);
	public void setGeneratorEntitys(Set generatorEntity){
		this.generatorEntitys = generatorEntity;
	}
	
	public Set<GeneratorEntity> getGeneratorEntitys() {
		return generatorEntitys;
	}
	
	private GeneratorDbserver generatorDbserver;
	
	public void setGeneratorDbserver(GeneratorDbserver generatorDbserver){
		this.generatorDbserver = generatorDbserver;
	}
	
	public GeneratorDbserver getGeneratorDbserver() {
		return generatorDbserver;
	}
	
	private GeneratorWebserver generatorWebserver;
	
	public void setGeneratorWebserver(GeneratorWebserver generatorWebserver){
		this.generatorWebserver = generatorWebserver;
	}
	
	public GeneratorWebserver getGeneratorWebserver() {
		return generatorWebserver;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("Path",getPath())
			.append("Code",getCode())
			.append("Name",getName())
			.append("Basepackage",getBasepackage())
			.append("TemaplateName",getTemaplateName())
			.append("DbserverId",getDbserverId())
			.append("WebserverId",getWebserverId())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.append(getPath())
			.append(getCode())
			.append(getName())
			.append(getBasepackage())
			.append(getTemaplateName())
			.append(getDbserverId())
			.append(getWebserverId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof GeneratorProject == false) return false;
		if(this == obj) return true;
		GeneratorProject other = (GeneratorProject)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.append(getPath(),other.getPath())
			.append(getCode(),other.getCode())
			.append(getName(),other.getName())
			.append(getBasepackage(),other.getBasepackage())
			.append(getTemaplateName(),other.getTemaplateName())
			.append(getDbserverId(),other.getDbserverId())
			.append(getWebserverId(),other.getWebserverId())
			.isEquals();
	}
}

