//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-19 11:56:15
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.entity;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class GeneratorServiceMethod implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	
	//columns START
	private java.lang.Long id;
	private java.lang.String businessLogic;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.String consumes;
	private java.lang.String httpMethod;
	private java.lang.String producer;
	private java.lang.String subPath;
	private java.lang.String returnType;
	private java.lang.Long serviceId;
	//columns END

	public GeneratorServiceMethod(){
	}

	public GeneratorServiceMethod(
		java.lang.Long id
	){
		this.id = id;
	}

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	public java.lang.Long getId() {
		return this.id;
	}
	public void setBusinessLogic(java.lang.String value) {
		this.businessLogic = value;
	}
	
	public java.lang.String getBusinessLogic() {
		return this.businessLogic;
	}
	public void setCode(java.lang.String value) {
		this.code = value;
	}
	
	public java.lang.String getCode() {
		return this.code;
	}
	public void setName(java.lang.String value) {
		this.name = value;
	}
	
	public java.lang.String getName() {
		return this.name;
	}
	public void setConsumes(java.lang.String value) {
		this.consumes = value;
	}
	
	public java.lang.String getConsumes() {
		return this.consumes;
	}
	public void setHttpMethod(java.lang.String value) {
		this.httpMethod = value;
	}
	
	public java.lang.String getHttpMethod() {
		return this.httpMethod;
	}
	public void setProducer(java.lang.String value) {
		this.producer = value;
	}
	
	public java.lang.String getProducer() {
		return this.producer;
	}
	public void setSubPath(java.lang.String value) {
		this.subPath = value;
	}
	
	public java.lang.String getSubPath() {
		return this.subPath;
	}
	public void setReturnType(java.lang.String value) {
		this.returnType = value;
	}
	
	public java.lang.String getReturnType() {
		return this.returnType;
	}
	public void setServiceId(java.lang.Long value) {
		this.serviceId = value;
	}
	
	public java.lang.Long getServiceId() {
		return this.serviceId;
	}
	
	private Set<GeneratorMethodParam> generatorMethodParams = new HashSet<GeneratorMethodParam>(0);
	public void setGeneratorMethodParams(Set generatorMethodParam){
		this.generatorMethodParams = generatorMethodParam;
	}
	
	public Set<GeneratorMethodParam> getGeneratorMethodParams() {
		return generatorMethodParams;
	}
	
	private GeneratorService generatorService;
	
	public void setGeneratorService(GeneratorService generatorService){
		this.generatorService = generatorService;
	}
	
	public GeneratorService getGeneratorService() {
		return generatorService;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("BusinessLogic",getBusinessLogic())
			.append("Code",getCode())
			.append("Name",getName())
			.append("Consumes",getConsumes())
			.append("HttpMethod",getHttpMethod())
			.append("Producer",getProducer())
			.append("SubPath",getSubPath())
			.append("ReturnType",getReturnType())
			.append("ServiceId",getServiceId())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.append(getBusinessLogic())
			.append(getCode())
			.append(getName())
			.append(getConsumes())
			.append(getHttpMethod())
			.append(getProducer())
			.append(getSubPath())
			.append(getReturnType())
			.append(getServiceId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof GeneratorServiceMethod == false) return false;
		if(this == obj) return true;
		GeneratorServiceMethod other = (GeneratorServiceMethod)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.append(getBusinessLogic(),other.getBusinessLogic())
			.append(getCode(),other.getCode())
			.append(getName(),other.getName())
			.append(getConsumes(),other.getConsumes())
			.append(getHttpMethod(),other.getHttpMethod())
			.append(getProducer(),other.getProducer())
			.append(getSubPath(),other.getSubPath())
			.append(getReturnType(),other.getReturnType())
			.append(getServiceId(),other.getServiceId())
			.isEquals();
	}
}

