//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-28 15:43:13
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.entity;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class GeneratorDbserver implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	
	//columns START
	private java.lang.Long id;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.String dbType;
	private java.lang.String jdbcUrl;
	private java.lang.String username;
	private java.lang.String password;
	private java.lang.String dialect;
	private java.lang.String driverClass;
	//columns END

	public GeneratorDbserver(){
	}

	public GeneratorDbserver(
		java.lang.Long id
	){
		this.id = id;
	}

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	public java.lang.Long getId() {
		return this.id;
	}
	public void setCode(java.lang.String value) {
		this.code = value;
	}
	
	public java.lang.String getCode() {
		return this.code;
	}
	public void setName(java.lang.String value) {
		this.name = value;
	}
	
	public java.lang.String getName() {
		return this.name;
	}
	public void setDbType(java.lang.String value) {
		this.dbType = value;
	}
	
	public java.lang.String getDbType() {
		return this.dbType;
	}
	public void setJdbcUrl(java.lang.String value) {
		this.jdbcUrl = value;
	}
	
	public java.lang.String getJdbcUrl() {
		return this.jdbcUrl;
	}
	public void setUsername(java.lang.String value) {
		this.username = value;
	}
	
	public java.lang.String getUsername() {
		return this.username;
	}
	public void setPassword(java.lang.String value) {
		this.password = value;
	}
	
	public java.lang.String getPassword() {
		return this.password;
	}
	public void setDialect(java.lang.String value) {
		this.dialect = value;
	}
	
	public java.lang.String getDialect() {
		return this.dialect;
	}
	public void setDriverClass(java.lang.String value) {
		this.driverClass = value;
	}
	
	public java.lang.String getDriverClass() {
		return this.driverClass;
	}
	
	private Set<GeneratorProject> generatorProjects = new HashSet<GeneratorProject>(0);
	public void setGeneratorProjects(Set generatorProject){
		this.generatorProjects = generatorProject;
	}
	
	public Set<GeneratorProject> getGeneratorProjects() {
		return generatorProjects;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("Code",getCode())
			.append("Name",getName())
			.append("DbType",getDbType())
			.append("JdbcUrl",getJdbcUrl())
			.append("Username",getUsername())
			.append("Password",getPassword())
			.append("Dialect",getDialect())
			.append("DriverClass",getDriverClass())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.append(getCode())
			.append(getName())
			.append(getDbType())
			.append(getJdbcUrl())
			.append(getUsername())
			.append(getPassword())
			.append(getDialect())
			.append(getDriverClass())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof GeneratorDbserver == false) return false;
		if(this == obj) return true;
		GeneratorDbserver other = (GeneratorDbserver)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.append(getCode(),other.getCode())
			.append(getName(),other.getName())
			.append(getDbType(),other.getDbType())
			.append(getJdbcUrl(),other.getJdbcUrl())
			.append(getUsername(),other.getUsername())
			.append(getPassword(),other.getPassword())
			.append(getDialect(),other.getDialect())
			.append(getDriverClass(),other.getDriverClass())
			.isEquals();
	}
}

