//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-14 10:01:25
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.entity;

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.codehaus.jackson.annotate.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
@JsonIgnoreProperties(value={"hibernateLazyInitializer","handler"}) 
public class GeneratorEntity implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	
	//columns START
	private java.lang.Long id;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.Long projectId;
	//columns END

	public GeneratorEntity(){
	}

	public GeneratorEntity(
		java.lang.Long id
	){
		this.id = id;
	}

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	public java.lang.Long getId() {
		return this.id;
	}
	public void setCode(java.lang.String value) {
		this.code = value;
	}
	
	public java.lang.String getCode() {
		return this.code;
	}
	public void setName(java.lang.String value) {
		this.name = value;
	}
	
	public java.lang.String getName() {
		return this.name;
	}
	public void setProjectId(java.lang.Long value) {
		this.projectId = value;
	}
	
	public java.lang.Long getProjectId() {
		return this.projectId;
	}
	@JsonIgnore
	private Set<GeneratorField> generatorFields = new HashSet<GeneratorField>(0);
	public void setGeneratorFields(Set generatorField){
		this.generatorFields = generatorField;
	}
	
	public Set<GeneratorField> getGeneratorFields() {
		return generatorFields;
	}
	@JsonIgnore
	private GeneratorProject generatorProject;
	
	public void setGeneratorProject(GeneratorProject generatorProject){
		this.generatorProject = generatorProject;
	}
	
	public GeneratorProject getGeneratorProject() {
		return generatorProject;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("Code",getCode())
			.append("Name",getName())
			.append("ProjectId",getProjectId())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.append(getCode())
			.append(getName())
			.append(getProjectId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof GeneratorEntity == false) return false;
		if(this == obj) return true;
		GeneratorEntity other = (GeneratorEntity)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.append(getCode(),other.getCode())
			.append(getName(),other.getName())
			.append(getProjectId(),other.getProjectId())
			.isEquals();
	}
}

