//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-01-19 11:56:14
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.entity;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class GeneratorService implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	
	//columns START
	private java.lang.Long id;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.Integer implType;
	private java.lang.String uri;
	private java.lang.Integer serviceType;
	private java.lang.String path;
	private java.lang.Long projectId;
	//columns END

	public GeneratorService(){
	}

	public GeneratorService(
		java.lang.Long id
	){
		this.id = id;
	}

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	public java.lang.Long getId() {
		return this.id;
	}
	public void setCode(java.lang.String value) {
		this.code = value;
	}
	
	public java.lang.String getCode() {
		return this.code;
	}
	public void setName(java.lang.String value) {
		this.name = value;
	}
	
	public java.lang.String getName() {
		return this.name;
	}
	public void setImplType(java.lang.Integer value) {
		this.implType = value;
	}
	
	public java.lang.Integer getImplType() {
		return this.implType;
	}
	public void setUri(java.lang.String value) {
		this.uri = value;
	}
	
	public java.lang.String getUri() {
		return this.uri;
	}
	public void setServiceType(java.lang.Integer value) {
		this.serviceType = value;
	}
	
	public java.lang.Integer getServiceType() {
		return this.serviceType;
	}
	public void setPath(java.lang.String value) {
		this.path = value;
	}
	
	public java.lang.String getPath() {
		return this.path;
	}
	public void setProjectId(java.lang.Long value) {
		this.projectId = value;
	}
	
	public java.lang.Long getProjectId() {
		return this.projectId;
	}
	
	private Set<GeneratorServiceMethod> generatorServiceMethods = new HashSet<GeneratorServiceMethod>(0);
	public void setGeneratorServiceMethods(Set generatorServiceMethod){
		this.generatorServiceMethods = generatorServiceMethod;
	}
	
	public Set<GeneratorServiceMethod> getGeneratorServiceMethods() {
		return generatorServiceMethods;
	}
	
	private GeneratorProject generatorProject;
	
	public void setGeneratorProject(GeneratorProject generatorProject){
		this.generatorProject = generatorProject;
	}
	
	public GeneratorProject getGeneratorProject() {
		return generatorProject;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("Code",getCode())
			.append("Name",getName())
			.append("ImplType",getImplType())
			.append("Uri",getUri())
			.append("ServiceType",getServiceType())
			.append("Path",getPath())
			.append("ProjectId",getProjectId())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.append(getCode())
			.append(getName())
			.append(getImplType())
			.append(getUri())
			.append(getServiceType())
			.append(getPath())
			.append(getProjectId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof GeneratorService == false) return false;
		if(this == obj) return true;
		GeneratorService other = (GeneratorService)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.append(getCode(),other.getCode())
			.append(getName(),other.getName())
			.append(getImplType(),other.getImplType())
			.append(getUri(),other.getUri())
			.append(getServiceType(),other.getServiceType())
			.append(getPath(),other.getPath())
			.append(getProjectId(),other.getProjectId())
			.isEquals();
	}
}

