//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-03-25 15:47:29
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.entity;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class GenModel implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	
	//columns START
	private java.lang.Long id;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.Long projectId;
	private java.lang.Long systemAuto;
	//columns END

	public GenModel(){
	}

	public GenModel(
		java.lang.Long id
	){
		this.id = id;
	}

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	public java.lang.Long getId() {
		return this.id;
	}
	public void setCode(java.lang.String value) {
		this.code = value;
	}
	
	public java.lang.String getCode() {
		return this.code;
	}
	public void setName(java.lang.String value) {
		this.name = value;
	}
	
	public java.lang.String getName() {
		return this.name;
	}
	public void setProjectId(java.lang.Long value) {
		this.projectId = value;
	}
	
	public java.lang.Long getProjectId() {
		return this.projectId;
	}
	public void setSystemAuto(java.lang.Long value) {
		this.systemAuto = value;
	}
	
	public java.lang.Long getSystemAuto() {
		return this.systemAuto;
	}
	
	private Set<GenController> genControllers = new HashSet<GenController>(0);
	public void setGenControllers(Set genController){
		this.genControllers = genController;
	}
	
	public Set<GenController> getGenControllers() {
		return genControllers;
	}
	
	private Set<GenModelProperty> genModelPropertys = new HashSet<GenModelProperty>(0);
	public void setGenModelPropertys(Set genModelProperty){
		this.genModelPropertys = genModelProperty;
	}
	
	public Set<GenModelProperty> getGenModelPropertys() {
		return genModelPropertys;
	}
	
	private GeneratorProject generatorProject;
	
	public void setGeneratorProject(GeneratorProject generatorProject){
		this.generatorProject = generatorProject;
	}
	
	public GeneratorProject getGeneratorProject() {
		return generatorProject;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("Code",getCode())
			.append("Name",getName())
			.append("ProjectId",getProjectId())
			.append("SystemAuto",getSystemAuto())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.append(getCode())
			.append(getName())
			.append(getProjectId())
			.append(getSystemAuto())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof GenModel == false) return false;
		if(this == obj) return true;
		GenModel other = (GenModel)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.append(getCode(),other.getCode())
			.append(getName(),other.getName())
			.append(getProjectId(),other.getProjectId())
			.append(getSystemAuto(),other.getSystemAuto())
			.isEquals();
	}
}

