//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-03-25 15:47:30
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.entity;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class GenModelProperty implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	
	//columns START
	private java.lang.Long id;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.Long modeId;
	private java.lang.Long dataTypeId;
	private java.lang.Long entityTypeId;
	private java.lang.Long type;
	//columns END

	public GenModelProperty(){
	}

	public GenModelProperty(
		java.lang.Long id
	){
		this.id = id;
	}

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	public java.lang.Long getId() {
		return this.id;
	}
	public void setCode(java.lang.String value) {
		this.code = value;
	}
	
	public java.lang.String getCode() {
		return this.code;
	}
	public void setName(java.lang.String value) {
		this.name = value;
	}
	
	public java.lang.String getName() {
		return this.name;
	}
	public void setModeId(java.lang.Long value) {
		this.modeId = value;
	}
	
	public java.lang.Long getModeId() {
		return this.modeId;
	}
	public void setDataTypeId(java.lang.Long value) {
		this.dataTypeId = value;
	}
	
	public java.lang.Long getDataTypeId() {
		return this.dataTypeId;
	}
	public void setEntityTypeId(java.lang.Long value) {
		this.entityTypeId = value;
	}
	
	public java.lang.Long getEntityTypeId() {
		return this.entityTypeId;
	}
	public void setType(java.lang.Long value) {
		this.type = value;
	}
	
	public java.lang.Long getType() {
		return this.type;
	}
	
	private GeneratorDataType generatorDataType;
	
	public void setGeneratorDataType(GeneratorDataType generatorDataType){
		this.generatorDataType = generatorDataType;
	}
	
	public GeneratorDataType getGeneratorDataType() {
		return generatorDataType;
	}
	
	private GeneratorEntity generatorEntity;
	
	public void setGeneratorEntity(GeneratorEntity generatorEntity){
		this.generatorEntity = generatorEntity;
	}
	
	public GeneratorEntity getGeneratorEntity() {
		return generatorEntity;
	}
	
	private GenModel genModel;
	
	public void setGenModel(GenModel genModel){
		this.genModel = genModel;
	}
	
	public GenModel getGenModel() {
		return genModel;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("Code",getCode())
			.append("Name",getName())
			.append("ModeId",getModeId())
			.append("DataTypeId",getDataTypeId())
			.append("EntityTypeId",getEntityTypeId())
			.append("Type",getType())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.append(getCode())
			.append(getName())
			.append(getModeId())
			.append(getDataTypeId())
			.append(getEntityTypeId())
			.append(getType())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof GenModelProperty == false) return false;
		if(this == obj) return true;
		GenModelProperty other = (GenModelProperty)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.append(getCode(),other.getCode())
			.append(getName(),other.getName())
			.append(getModeId(),other.getModeId())
			.append(getDataTypeId(),other.getDataTypeId())
			.append(getEntityTypeId(),other.getEntityTypeId())
			.append(getType(),other.getType())
			.isEquals();
	}
}

