//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-03-25 15:47:29
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.entity;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class GenPropType implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	
	//columns START
	private java.lang.Long id;
	private java.lang.String typeKey;
	private java.lang.String typeName;
	//columns END

	public GenPropType(){
	}

	public GenPropType(
		java.lang.Long id
	){
		this.id = id;
	}

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	public java.lang.Long getId() {
		return this.id;
	}
	public void setTypeKey(java.lang.String value) {
		this.typeKey = value;
	}
	
	public java.lang.String getTypeKey() {
		return this.typeKey;
	}
	public void setTypeName(java.lang.String value) {
		this.typeName = value;
	}
	
	public java.lang.String getTypeName() {
		return this.typeName;
	}
	
	private Set<GenUiPropertity> genUiPropertitys = new HashSet<GenUiPropertity>(0);
	public void setGenUiPropertitys(Set genUiPropertity){
		this.genUiPropertitys = genUiPropertity;
	}
	
	public Set<GenUiPropertity> getGenUiPropertitys() {
		return genUiPropertitys;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("TypeKey",getTypeKey())
			.append("TypeName",getTypeName())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.append(getTypeKey())
			.append(getTypeName())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof GenPropType == false) return false;
		if(this == obj) return true;
		GenPropType other = (GenPropType)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.append(getTypeKey(),other.getTypeKey())
			.append(getTypeName(),other.getTypeName())
			.isEquals();
	}
}

