//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由模板自动生成 - 2016-03-25 15:47:26
//     对此文件的更改可能会导致不正确的行为，并且如果 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
package com.bonc.quickframework.entity;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.codehaus.jackson.annotate.JsonIgnore;

import java.util.*;

/**
 * @author dguanlin email:dguanlin(a)163.com
 * @version 1.0
 * @since 1.0
 */
 
public class GenUi implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	
	//columns START
	private java.lang.Long id;
	private java.lang.String code;
	private java.lang.String name;
	//columns END

	public GenUi(){
	}

	public GenUi(
		java.lang.Long id
	){
		this.id = id;
	}

	public void setId(java.lang.Long value) {
		this.id = value;
	}
	
	public java.lang.Long getId() {
		return this.id;
	}
	public void setCode(java.lang.String value) {
		this.code = value;
	}
	
	public java.lang.String getCode() {
		return this.code;
	}
	public void setName(java.lang.String value) {
		this.name = value;
	}
	
	public java.lang.String getName() {
		return this.name;
	}
	@JsonIgnore
	private Set<GenUiPropertity> genUiPropertitys = new HashSet<GenUiPropertity>(0);
	public void setGenUiPropertitys(Set genUiPropertity){
		this.genUiPropertitys = genUiPropertity;
	}
	
	public Set<GenUiPropertity> getGenUiPropertitys() {
		return genUiPropertitys;
	}
	@JsonIgnore
	private Set<GenUiDetail> genUiDetails = new HashSet<GenUiDetail>(0);
	public void setGenUiDetails(Set genUiDetail){
		this.genUiDetails = genUiDetail;
	}
	
	public Set<GenUiDetail> getGenUiDetails() {
		return genUiDetails;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("Code",getCode())
			.append("Name",getName())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.append(getCode())
			.append(getName())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof GenUi == false) return false;
		if(this == obj) return true;
		GenUi other = (GenUi)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.append(getCode(),other.getCode())
			.append(getName(),other.getName())
			.isEquals();
	}
}

